# Generated by Django 4.1.2 on 2022-10-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Option', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=24)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=20)),
                ('Age', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=20)),
            ],
        ),
    ]
