# Generated by Django 4.1.2 on 2022-10-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0002_legaladvisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='buysell',
            name='Option',
            field=models.CharField(choices=[('L', 'LegalAdvisor'), ('U', 'User')], default='U', max_length=20),
        ),
        migrations.AddField(
            model_name='buysell',
            name='is_legal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buysell',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legaladvisor',
            name='is_legal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legaladvisor',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='legaladvisor',
            name='Option',
            field=models.CharField(choices=[('L', 'LegalAdvisor'), ('U', 'User')], default='U', max_length=20),
        ),
    ]
