# Generated by Django 4.1.2 on 2022-10-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0003_buysell_option_buysell_is_legal_buysell_is_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buysell',
            name='Option',
        ),
        migrations.RemoveField(
            model_name='buysell',
            name='is_legal',
        ),
        migrations.RemoveField(
            model_name='buysell',
            name='is_user',
        ),
        migrations.RemoveField(
            model_name='legaladvisor',
            name='Option',
        ),
        migrations.RemoveField(
            model_name='legaladvisor',
            name='is_legal',
        ),
        migrations.RemoveField(
            model_name='legaladvisor',
            name='is_user',
        ),
    ]
