# Generated by Django 4.1.2 on 2022-10-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0004_remove_buysell_option_remove_buysell_is_legal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legaladvisor',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='legaladvisor',
            old_name='Name',
            new_name='name',
        ),
    ]
