# Generated by Django 4.1.2 on 2022-10-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0005_rename_email_legaladvisor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buysell',
            name='Age',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='buysell',
            name='Phone',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='legaladvisor',
            name='License',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
