# Generated by Django 4.1.2 on 2022-10-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0006_buysell_age_buysell_phone_legaladvisor_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaladvisor',
            name='File',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='files/'),
        ),
    ]
