# Generated by Django 4.1.2 on 2022-10-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0007_legaladvisor_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaladvisor',
            name='File',
            field=models.FileField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='legaladvisor',
            name='License',
            field=models.CharField(max_length=20),
        ),
    ]
