# Generated by Django 4.1.2 on 2022-11-02 15:08

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0008_alter_legaladvisor_file_alter_legaladvisor_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaladvisor',
            name='File',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='upload/'),
        ),
    ]
