# Generated by Django 4.1.2 on 2022-11-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0009_alter_legaladvisor_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaladvisor',
            name='File',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
