# Generated by Django 4.1.2 on 2022-11-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0010_alter_legaladvisor_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaladvisor',
            name='File',
            field=models.FileField(upload_to='upload'),
        ),
    ]
