# Generated by Django 4.1.2 on 2022-11-17 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buysell', '0011_alter_legaladvisor_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='legaladvisor',
            name='file_url',
            field=models.URLField(default=0),
        ),
        migrations.CreateModel(
            name='Addproperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(default=0, max_length=254)),
                ('postal', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('des', models.CharField(max_length=255)),
                ('File', models.ImageField(upload_to='upload')),
                ('File_url', models.URLField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buysell.city')),
            ],
        ),
    ]
